name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: "Label issues"
        uses: actions/labeler@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
